{% set version = environ.get("HOLOSCAN_VERSION", "4.3.0.1") %}

package:
  name: holoscan
  version: {{ version }}

source:
  - url: "https://files.pythonhosted.org/packages/7f/de/c332470b67b5f8037d4a0a93197bd0d04d767d8b96a6d7330006cab37b41/holoscan_cu13-4.3.0-cp310-cp310-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 310]
    sha256: "5574e63c5893816f8a47d6a45e12d94ed9e2b2d187da30ab53f2ac65c7c2f46b"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 310]
  - url: "https://files.pythonhosted.org/packages/bc/2e/d00b715312e0326f60e1c7d1226426bf2ca9bde4d02f68b8f85be5cf0c03/holoscan_cu13-4.3.0-cp311-cp311-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 311]
    sha256: "c072ac4a263e6d5f0fef2aecfc2ff4192244c391776c2773c50d87b9cd9e2527"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 311]
  - url: "https://files.pythonhosted.org/packages/ac/ad/ca83b187036bc49f19ee8fba9f1f70175cb3aa208caaffa08a1ba840a505/holoscan_cu13-4.3.0-cp312-cp312-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 312]
    sha256: "66d8bf684daee5981a3d22d4e36adee41116af8bbabf1acc7ea54b3e946ad91a"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 312]
  - url: "https://files.pythonhosted.org/packages/d1/94/8f81a2706e607c017622d3d89ee270fb104f0ef23b4fc386eeb296bbb0ff/holoscan_cu13-4.3.0-cp313-cp313-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 313]
    sha256: "c46412cd9090e8ad2981105a6a9d3305c65121011f97a29120f3875be8576043"  # [linux64 and (cuda_compiler_version or "").startswith("13") and py == 313]

  - url: "https://files.pythonhosted.org/packages/85/b2/54b01def0baad7e46bccf7aad5430b908ae192007322f62d3c1811d743ac/holoscan_cu13-4.3.0-cp310-cp310-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 310]
    sha256: "d82507863fc9a5615ec43b1ef95cc277a0e78599342917bb967f979920c618a8"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 310]
  - url: "https://files.pythonhosted.org/packages/26/4a/02a025a453fe23f4fa84ad957b4c2d21a6e111e3a38e5e228e0c7687a566/holoscan_cu13-4.3.0-cp311-cp311-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 311]
    sha256: "58db0d9fa9d20a72719796321a9f125fa8c478e853e31e8337a8a87c57940367"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 311]
  - url: "https://files.pythonhosted.org/packages/69/ae/78fd24a5de28bcd8d7afe6b2e72200bdd34a071e73fb37d29b721314808b/holoscan_cu13-4.3.0-cp312-cp312-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 312]
    sha256: "1a53cad723cb7d139fdcba9ea8a6ebe20dfbd3fefb6b5a76a9774bdf9e52adad"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 312]
  - url: "https://files.pythonhosted.org/packages/5f/b4/43f00b9de8cb5c76c4ff16eaa46e5bcec6f764e482ad80ccf770e722d50c/holoscan_cu13-4.3.0-cp313-cp313-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 313]
    sha256: "a45b161744854cd70881b993617053873f6aa0f0a048a247c2d7f2ec29ed40c3"  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa" and py == 313]

build:
  number: 1
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None", "") or (cuda_compiler_version or "").startswith("11") or (cuda_compiler_version or "").startswith("12")]
  skip: true  # [py<310 or py>313]
  missing_dso_whitelist:
    - "*libcuda.so*"              # driver, not provided by any conda package
    - "*librmm.so*"               # RMM, available in RAPIDS channel
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python
    - cf-nvidia-tools 1  # [linux]
  host:
    - libholoscan {{ version }}
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools
    - pip
  run:
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    - cloudpickle >=3.0
    - cuda-version >={{ cuda_compiler_version_min }}
    - cupy
    - libholoscan {{ version }}.*
    - cuda-cudart
    - python

test:
  # imports:
  #   - holoscan
  requires:
    - pip
  commands:
    - test -d $SP_DIR/holoscan/
    - pip check

about:
  home: https://docs.nvidia.com/cuda/holoscan/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - NOTICE
  license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
  summary: NVIDIA Holoscan python bindings
  description: |
    NVIDIA Holoscan python bindings

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: holoscan
