{% set version = "4.2.0.1" %}

package:
  name: holoscan
  version: {{ version }}

source:
  - url: "https://files.pythonhosted.org/packages/de/20/8cd0adc3ebc00d9da3303515bc22ff2de7c3a3031f16ce1f3f1b070fbda9/holoscan_cu12-4.2.0-cp310-cp310-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 310]
    sha256: "ac0030a407049aeeca20b1347ff50906f9c0172cc03821e8175423e365aebe8b"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 310]
  - url: "https://files.pythonhosted.org/packages/c0/77/c6d97e0264fc96d3cb63bf613772889ec285331f4ea4fcaecf2a739c3ff3/holoscan_cu12-4.2.0-cp311-cp311-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 311]
    sha256: "4079c9ec29e07c567dbd498c1a49b8111a52def7bc4f83f4ce9fa0aae1f2cece"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 311]
  - url: "https://files.pythonhosted.org/packages/86/62/36a6de42f4e160d4c5f299f8a2ef08951c83d9a4e8ce8c4afb8ac239f351/holoscan_cu12-4.2.0-cp312-cp312-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 312]
    sha256: "3a5e0cce84d94a4cc461a8a362592ebd8106198dcc8b33f10c871d6fbe1d5c45"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 312]
  - url: "https://files.pythonhosted.org/packages/c7/3e/23b21939ce0416072539cceb9883acfb61cf6a1f2017faf8460ad1d8dca1/holoscan_cu12-4.2.0-cp313-cp313-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 313]
    sha256: "50a6bfc917c068ee442c059b5e5669a4e0a5bcaa5836b9fa356374332dfbebb0"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 313]

  - url: "https://files.pythonhosted.org/packages/01/b6/040798edba0f5c416d6e9ff3aeb0537aa21644e98fe38ca7b14e7c213a7e/holoscan_cu12-4.2.0-cp310-cp310-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 310]
    sha256: "d98dace790ef82c50a20b25219e7650c8af9f7423aa07e3b54eb8bba52028a91"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 310]
  - url: "https://files.pythonhosted.org/packages/77/82/1af146aee078aae77636fdff7a7ded9ef3483cf03653f31969b705f79e2c/holoscan_cu12-4.2.0-cp311-cp311-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 311]
    sha256: "815d62c19384421fa5a7a512be9b2230a66cd7aa08b24fbe9df250d912f53dd3"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 311]
  - url: "https://files.pythonhosted.org/packages/22/92/a9d10566bac9296dfbbca4b8536f223ad5bdd91a6a01ccf88f38335af2b4/holoscan_cu12-4.2.0-cp312-cp312-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 312]
    sha256: "86d040f2c951fa9dcdfbbc5b77da569aa3706978cd8ee145813edf9922a8cf08"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 312]
  - url: "https://files.pythonhosted.org/packages/33/e4/2589e5ddf6489fddd950917f1a9c17967f823288d9ff03bb698378a46e8f/holoscan_cu12-4.2.0-cp313-cp313-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 313]
    sha256: "2c9e9708a8fa66d87f5cf0aa6118350c839b190bb10801e2d745c9c0c9796b1e"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 313]

build:
  number: 0
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None", "") or (cuda_compiler_version or "").startswith("11")]
  skip: true  # [py<310 or py>313]
  missing_dso_whitelist:
    - "*librmm.so*"               # RMM, available in RAPIDS channel
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python
    - cf-nvidia-tools 1  # [linux]
  host:
    - libholoscan {{ version }}
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools
    - pip
  run:
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    - cloudpickle >=3.0
    - cuda-version >={{ cuda_compiler_version_min }}
    - cupy
    - libholoscan {{ version }}.*
    - cuda-cudart
    - python

test:
  # imports:
  #   - holoscan
  requires:
    - pip
  commands:
    - test -d $SP_DIR/holoscan/
    - pip check

about:
  home: https://docs.nvidia.com/cuda/holoscan/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - NOTICE
  license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
  summary: NVIDIA Holoscan python bindings
  description: |
    NVIDIA Holoscan python bindings

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: holoscan
