{% set version = "3.10.0.0" %}

package:
  name: holoscan
  version: {{ version }}

source:
  - url: "https://files.pythonhosted.org/packages/e8/7c/7a6d598c08d29e75789e40c052de922be688de30e9b7df91bfc62459dc75/holoscan_cu12-3.10.0-cp310-cp310-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 310]
    sha256: "823ecf47553038fcba906f998baa992df790bb56bc14ca2484ff24f7e054a463"  # [linux64 and (cuda_compiler_version or "").startswith("12" ) and py == 310]
  - url: "https://files.pythonhosted.org/packages/d0/52/85a6e6bd4f2710a17413b43dd69ea0d12f82660b86a879a6b3d1606fcd19/holoscan_cu12-3.10.0-cp311-cp311-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 311]
    sha256: "3e1a1bc035d9143dc0c3b4d74155d9aa09feff795e20cfc1980aabccf4f86d11"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 311]
  - url: "https://files.pythonhosted.org/packages/0a/3e/97a08e37c9efefefb1e7b48f8da707efc69d21ee94914fa249c422a1b383/holoscan_cu12-3.10.0-cp312-cp312-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 312]
    sha256: "d9734c1a7ea1ae745089b927f80585bd62d367aa56f1ab40c525780a92c95673"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 312]
  - url: "https://files.pythonhosted.org/packages/6f/f8/e27ab9e298d88f3fb55af3a0f0ef1d3939e49bc9a63f4114b706aac5c9fe/holoscan_cu12-3.10.0-cp313-cp313-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 313]
    sha256: "dc26f81a4a0e17adafba695b554dba1e68c98af73d456a177aaebef0c26bb45b"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 313]

  - url: "https://files.pythonhosted.org/packages/b5/1d/f6f97b4f1a826e4577dba3f21795b474167366913f925c40e9b9ed64d8a7/holoscan_cu12-3.10.0-cp310-cp310-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 310]
    sha256: "64f754618c55a4595bf5840c71c22c371e8cff3c7489d0317cd1307fbe8c6586"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 310]
  - url: "https://files.pythonhosted.org/packages/2e/70/e6b13ad9f29c497af1aa6ca33d44e4fb0b290656b796adf2f86dcd690e52/holoscan_cu12-3.10.0-cp311-cp311-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 311]
    sha256: "668a7de144eb309b5e5595a55b98c4ef7d3d0428836164c364f494fcd2c2dbd0"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 311]
  - url: "https://files.pythonhosted.org/packages/be/7b/fd2a07a84ea81d38e5589595ef8a688c337d185cb00161279895fffe1d6e/holoscan_cu12-3.10.0-cp312-cp312-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 312]
    sha256: "423048d9d08e9a1e4033c8eba15b44623d2793a08e7946f396ed4d6624b72f38"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 312]
  - url: "https://files.pythonhosted.org/packages/63/64/e5696e8694c71bbe556f7ecfcd91a3974ce6048c1446474a4d429f389374/holoscan_cu12-3.10.0-cp313-cp313-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 313]
    sha256: "1926e5619b877acad0455a8bae01c1cc3bc86819e7a7824fa18e77f8cd3969e9"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 313]

build:
  number: 1
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None", "") or (cuda_compiler_version or "").startswith("11")]
  skip: true  # [py<310 or py>313]
  missing_dso_whitelist:
    - "*librmm.so*"               # RMM, available in RAPIDS channel
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python
    - cf-nvidia-tools 1  # [linux]
  host:
    - libholoscan {{ version }}
    - cuda-version {{ cuda_compiler_version_min }}
    - python
    - setuptools
    - pip
  run:
    - cupy
    - libholoscan {{ version }}
    - cuda-cudart
    - python

test:
  # imports:
  #   - holoscan
  requires:
    - pip
  commands:
    - test -d $PREFIX/lib/python{{ python }}/site-packages/holoscan/
    - pip check

about:
  home: https://docs.nvidia.com/cuda/holoscan/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - NOTICE
  license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
  summary: NVIDIA Holoscan python bindings
  description: |
    NVIDIA Holoscan python bindings

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: holoscan
