{% set version = "3.8.0.1" %}
{% set abiversion = version.split('.')[0] %}
{% set libversion = version.split('.')[:3] | join('.') %}
{% set libtorch_version = "2.7.*" %}
{% set onnx_version = "1.22.*" %}
{% set ucx_version = "1.19.0.*" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}    # [aarch64]
{% set extension = "tar.xz" %}

{% set sha256 = "4e3899e78906342bae42d824005736deb15e1040360273286de5e3f7c883f83d" %}  # [linux64]
{% set sha256 = "3a7dd7e97021c5d1675a80633d6d917c5f1adafc0abdbf631602682020839807" %}  # [aarch64 and arm_variant_type == "sbsa"]

package:
  name: holoscan-split
  version: {{ version }}

source:
  - url: "https://files.pythonhosted.org/packages/eb/50/3e29af06593177f1ffdb7956bdc74402f382c2316b5e12e9fcd9c46ac59d/holoscan_cu12-3.8.0-cp310-cp310-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 310]
    sha256: "55c241b35964a150d299a7f83f8d6c9b9838f3bfde17c336e4d8daddb733675c"  # [linux64 and (cuda_compiler_version or "").startswith("12" ) and py == 310]
  - url: "https://files.pythonhosted.org/packages/b7/f1/0c8aa32a4e82cda3beef094d17b2c3bbb98b6c30ed90cdd58944989c8be8/holoscan_cu12-3.8.0-cp311-cp311-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 311]
    sha256: "c36803d2db64280a4e8aa3e9bda787f451872a4fb11493dd7f6cafd4718d91b3"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 311]
  - url: "https://files.pythonhosted.org/packages/94/f0/5b080892b01eea42e19491fbf62c56094af91dd3bf2f980f56da6fa18065/holoscan_cu12-3.8.0-cp312-cp312-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 312]
    sha256: "cbf3c632c3c8a75988f7a1b6afbc355e51e965872410c46087eed2695ead48d4"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 312]
  - url: "https://files.pythonhosted.org/packages/02/b5/1754814e1b7ed6526ba69d36f276a2bc6959b641df20a291a05a7ab587a2/holoscan_cu12-3.8.0-cp313-cp313-manylinux_2_35_x86_64.whl"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 313]
    sha256: "dbe1c4dbe2ec0f3dabd91d3aba42a064d54e4b35c62d02f5a388e4e76c76fb2f"  # [linux64 and (cuda_compiler_version or "").startswith("12") and py == 313]

  - url: "https://files.pythonhosted.org/packages/c0/91/74c545fcbfc6bbfde3413ba84552f6139b8b5c4119d5788310a658b8e7c0/holoscan_cu12-3.8.0-cp310-cp310-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 310]
    sha256: "ad277942d8754689e4890516759eee68011ee76b9053a5be5f3ee75c2b4f5f23"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 310]
  - url: "https://files.pythonhosted.org/packages/49/8f/789d88af0517e231763beb2b6f13d88e69315ed86207f4ca01fb068c2ac6/holoscan_cu12-3.8.0-cp311-cp311-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 311]
    sha256: "7e11a69f5a3da851bdba26d854efa22b572226f45ecefac66ca0745574903fa9"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 311]
  - url: "https://files.pythonhosted.org/packages/f6/ee/449127e7a4b036ff4f8fa9031c3fcec0ce164bfd2aa0c121acf0f9eb0ea8/holoscan_cu12-3.8.0-cp312-cp312-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 312]
    sha256: "e3e90bf1d626d7b5a663ecb0cc3cfa6a3fadc87e50e498df051e70afac726ab2"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 312]
  - url: "https://files.pythonhosted.org/packages/48/f4/9d7ae081b7ba5ea6d5a8f2ff3a1ef82fd84aff1c1c51dd3d8040bff85c9e/holoscan_cu12-3.8.0-cp313-cp313-manylinux_2_35_aarch64.whl"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 313]
    sha256: "f905178f94894c851ed5e274b58b25a82526584e29e2e9c60fc2fbbe911c6dbd"  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa" and py == 313]

  - url: https://developer.download.nvidia.com/compute/holoscan/redist/holoscan/{{ platform }}/holoscan-{{ platform }}-{{ version }}_cuda12-archive.{{ extension }}
    sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None", "") or (cuda_compiler_version or "").startswith("11")]

requirements:
  build:
    - cf-nvidia-tools 1  # [linux]
    - python
  host:
    - python

outputs:
  - name: libholoscan
    build:
      missing_dso_whitelist:
        - "*libcuda.so*"              # driver
        - "*libgdrapi.so*"            # part of gdrcopy yet not pre-built for conda-forge channel
        - "*libnvidia-ml.so*"         # driver
        - "*libnvinfer_plugin.so*"    # NVIDIA's TensorRT not on conda-forge
        - "*libnvonnxparser.so*"      # NVIDIA's TensorRT not on conda-forge
        - "*libtorchvision.so*"       # not available even in torchvision package
        - "*libv4l2.so*"              # lideo4linux2 lib, not available
        - "*libxpmem.so*"             # XPMEM, Linux Cross-Memory Attach kernel module, not available
      ignore_run_exports:
        # we support cuda-version >= 12.6, < 13
        - cuda-version
      post-link: post-link
    files:
      - lib/libholo*.so.*
      - lib/gxf_extensions
      - lib/libgxf*.so
      - lib/libucxx.so
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version_min }}
        - cuda-nvrtc-dev
        - libjpeg-turbo
        - libnpp-dev
        - libtorch {{ libtorch_version }}
        - libtorch * cuda*
        - libvulkan-loader
        - ucx {{ ucx_version }}
        - onnxruntime-cpp  {{ onnx_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x") }}  # [cuda_compiler_version != "None"]
        - cloudpickle
        - cuda-cudart
        - dbus              # [aarch64]  # Without this, segfault happens during camera app test in https://github.com/nvidia-holoscan/holoscan-sdk/tree/main/python
        - libegl
        - libjpeg-turbo
        - libtorch * cuda*
        - libvulkan-loader
    test:
      commands:
        - test -L $PREFIX/lib/libholoscan_core.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_infer.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_infer_onnx_runtime.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_infer_torch.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_infer_utils.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_logger.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_async_ping_rx.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_async_ping_tx.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_bayer_demosaic.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_format_converter.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_gxf_codelet.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_holoviz.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_inference.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_inference_processor.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_ping_rx.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_ping_tensor_rx.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_ping_tensor_tx.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_ping_tx.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_segmentation_postprocessor.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_v4l2.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_video_stream_recorder.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_op_video_stream_replayer.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_profiler.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_spdlog_logger.so.{{ abiversion }}
        - test -L $PREFIX/lib/libholoscan_viz.so.{{ abiversion }}
        - test -f $PREFIX/lib/libholoscan_core.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_infer.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_infer_onnx_runtime.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_infer_torch.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_infer_utils.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_logger.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_async_ping_rx.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_async_ping_tx.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_bayer_demosaic.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_format_converter.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_gxf_codelet.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_holoviz.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_inference.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_inference_processor.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_ping_rx.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_ping_tensor_rx.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_ping_tensor_tx.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_ping_tx.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_segmentation_postprocessor.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_v4l2.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_video_stream_recorder.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_op_video_stream_replayer.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_profiler.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_spdlog_logger.so.{{ libversion }}
        - test -f $PREFIX/lib/libholoscan_viz.so.{{ libversion }}
        - test -f $PREFIX/lib/libgxf_app.so
        - test -f $PREFIX/lib/libgxf_core.so
        - test -f $PREFIX/lib/libgxf_cuda.so
        - test -f $PREFIX/lib/libgxf_logger.so
        - test -f $PREFIX/lib/libgxf_multimedia.so
        - test -f $PREFIX/lib/libgxf_rmm.so
        - test -f $PREFIX/lib/libgxf_sample.so
        - test -f $PREFIX/lib/libgxf_serialization.so
        - test -f $PREFIX/lib/libgxf_std.so
        - test -f $PREFIX/lib/libgxf_ucx.so
        - test -f $PREFIX/lib/gxf_extensions/libgxf_holoscan_wrapper.so
        - test -f $PREFIX/lib/gxf_extensions/libgxf_holoscan_wrapper_lib.so
        - test -f $PREFIX/lib/gxf_extensions/libgxf_ucx_holoscan.so
        - test -f $PREFIX/lib/gxf_extensions/libgxf_ucx_holoscan_lib.so
    about:
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file:
        - LICENSE
        - NOTICE
      license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
      summary: NVIDIA Holoscan runtime library
      description: |
        This is a runtime package only. Developers should install holoscan (python) and/or libholoscan-dev (C++ SDK) to build with Holoscan

  - name: holoscan
    build:
      skip: true  # [py<310 or py>313]
      string: "py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
      script: bash ${RECIPE_DIR}/bindings-build.sh
    files:
      #- lib/python{{ python }}/site-packages/gxf  # Dropped GXP support in holoscan 3.3.0 with GXF 5.5.0. It may be added back in the future.
      - lib/python{{ python }}/site-packages/holoscan
    requirements:
      build:
        - cf-nvidia-tools 1  # [linux]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}    # [build_platform != target_platform]
        - python {{ python }}
      host:
        - {{ pin_subpackage("libholoscan", exact=True) }}
        - cuda-version {{ cuda_compiler_version_min }}
        - python {{ python }}
        - setuptools
        - pip
      run:
        - cupy
        - {{ pin_subpackage("libholoscan", exact=True) }}
        - cuda-cudart
    test:
      imports:
        - holoscan
        #- gxf  # Dropped GXP support in holoscan 3.3.0 with GXF 5.5.0. It may be added back in the future
      requires:
        - pip
      commands:
        #- test -d $PREFIX/lib/python{{ python }}/site-packages/gxf  # Dropped GXP support in holoscan 3.3.0 with GXF 5.5.0. It may be added back in the future.
        - test -d $PREFIX/lib/python{{ python }}/site-packages/holoscan/
        - pip check
    about:
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file:
        - LICENSE
        - NOTICE
      license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
      summary: NVIDIA Holoscan python bindings
      description: |
        NVIDIA Holoscan python bindings

  - name: libholoscan-dev
    build:
      missing_dso_whitelist:
        - "*libcuda.so*"              # driver
      run_exports:
        - {{ pin_subpackage("libholoscan", max_pin="x") }}
    files:
      - bin/convert_gxf_entities_to_images.py
      - bin/convert_gxf_entities_to_video.py
      - bin/convert_video_to_gxf_entities.py
      - bin/ctest_time_comparison.py
      - bin/download_ngc_data
      - bin/generate_extension_uuids.py
      - bin/generate_gxf_manifest.py
      - bin/graph_surgeon.py
      - bin/gxe
      - bin/gxf_entity_codec.py
      - bin/get_cmake_cuda_archs.py
      - bin/holoscan
      - bin/test_plattern_validation.py
      - bin/video_validation.py
      - examples/
      - include/3rdparty
      - include/fmt
      - include/gxf
      - include/gxf_holoscan_wrapper
      - include/holoinfer
      - include/holoscan
      - include/holoviz
      - include/magic_enum.hpp
      - include/rmm
      - lib/libholo*.so
      - lib/cmake/holoscan
      - lib/libholo*.a
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - {{ pin_subpackage("libholoscan", exact=True) }}
        - cuda-version {{ cuda_compiler_version_min }}
      run:
        - {{ pin_subpackage("libholoscan", exact=True) }}
        - cuda-nvcc         # holoscan wants to explicitly install this as it is needed for holoscan public interface
        - cuda-cudart
        - cuda-cudart-dev   # holoscan wants to explicitly install this as it is needed for holoscan public interface
        - cuda-nvrtc-dev    # holoscan wants to explicitly install this as it is needed for holoscan public interface
        - libnpp-dev        # holoscan wants to explicitly install this as it is needed for holoscan public interface
        - yaml-cpp-static   # holoscan wants to explicitly install this as it is needed for holoscan public interface
    test:
      requires:
        - cmake
        - make
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cuda-libraries-dev # need all CTK libs to compile all examples
        - patch  # needed by one of the examples
        - yaml-cpp-static
      files:
        - compile_examples.sh
      commands:
        - test -f $PREFIX/bin/convert_gxf_entities_to_images.py
        - test -f $PREFIX/bin/convert_gxf_entities_to_video.py
        - test -f $PREFIX/bin/convert_video_to_gxf_entities.py
        - test -f $PREFIX/bin/ctest_time_comparison.py
        - test -f $PREFIX/bin/download_ngc_data
        - test -f $PREFIX/bin/generate_extension_uuids.py
        - test -f $PREFIX/bin/generate_gxf_manifest.py
        - test -f $PREFIX/bin/graph_surgeon.py
        - test -f $PREFIX/bin/gxe
        - test -f $PREFIX/bin/gxf_entity_codec.py
        - test -f $PREFIX/bin/get_cmake_cuda_archs.py
        - test -f $PREFIX/bin/holoscan
        - test -f $PREFIX/bin/video_validation.py
        - test -d $PREFIX/lib/cmake/holoscan
        - test -d $PREFIX/examples
        - test -d $PREFIX/include/3rdparty
        - test -d $PREFIX/include/fmt
        - test -d $PREFIX/include/gxf
        - test -d $PREFIX/include/gxf_holoscan_wrapper
        - test -d $PREFIX/include/holoinfer
        - test -d $PREFIX/include/holoscan
        - test -d $PREFIX/include/holoviz
        - test -f $PREFIX/include/magic_enum.hpp
        - test -d $PREFIX/include/rmm
        - test -L $PREFIX/lib/libholoinfer_utils.so
        - test -L $PREFIX/lib/libholoscan_core.so
        - test -L $PREFIX/lib/libholoscan_infer.so
        - test -L $PREFIX/lib/libholoscan_infer_onnx_runtime.so
        - test -L $PREFIX/lib/libholoscan_infer_torch.so
        - test -L $PREFIX/lib/libholoscan_infer_utils.so
        - test -L $PREFIX/lib/libholoscan_logger.so
        - test -L $PREFIX/lib/libholoscan_op_async_ping_rx.so
        - test -L $PREFIX/lib/libholoscan_op_async_ping_tx.so
        - test -L $PREFIX/lib/libholoscan_op_bayer_demosaic.so
        - test -L $PREFIX/lib/libholoscan_op_format_converter.so
        - test -L $PREFIX/lib/libholoscan_op_gxf_codelet.so
        - test -L $PREFIX/lib/libholoscan_op_holoviz.so
        - test -L $PREFIX/lib/libholoscan_op_inference.so
        - test -L $PREFIX/lib/libholoscan_op_inference_processor.so
        - test -L $PREFIX/lib/libholoscan_op_ping_rx.so
        - test -L $PREFIX/lib/libholoscan_op_ping_tensor_rx.so
        - test -L $PREFIX/lib/libholoscan_op_ping_tensor_tx.so
        - test -L $PREFIX/lib/libholoscan_op_ping_tx.so
        - test -L $PREFIX/lib/libholoscan_op_segmentation_postprocessor.so
        - test -L $PREFIX/lib/libholoscan_op_v4l2.so
        - test -L $PREFIX/lib/libholoscan_op_video_stream_recorder.so
        - test -L $PREFIX/lib/libholoscan_op_video_stream_replayer.so
        - test -L $PREFIX/lib/libholoscan_profiler.so
        - test -L $PREFIX/lib/libholoscan_spdlog_logger.so
        - test -L $PREFIX/lib/libholoscan_viz.so
        - test -f $PREFIX/lib/libholoviz_imgui.a
        - bash compile_examples.sh

about:
  home: https://docs.nvidia.com/cuda/holoscan/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - NOTICE
  license_url: https://developer.download.nvidia.com/assets/Clara/NVIDIA_Clara_EULA.pdf
  summary: NVIDIA Holoscan is the AI sensor processing platform that combines hardware systems for low-latency sensor and network connectivity, optimized libraries for data processing and AI, and core microservices to run streaming, imaging, and other applications, from embedded to edge to cloud.
  description: |
    NVIDIA Holoscan is the AI sensor processing platform that combines hardware systems for low-latency sensor and network connectivity, optimized libraries for data processing and AI, and core microservices to run streaming, imaging, and other applications, from embedded to edge to cloud.
    It can be used to build streaming AI pipelines for a variety of domains, including Medical Devices, High Performance Computing at the Edge, Industrial Inspection and more.
  doc_url: https://docs.nvidia.com/cuda/holoscan/

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: holoscan
